# -*- coding: utf-8 -*-
"""impactpy1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dr8MEbKGFEuHTL-vit0C-fpWeziSowSD
"""

pprint ("Hello world")

print ("hello python!")

counter = 100
miles =1000.0
name ="teja"
print (counter)
print (miles)
print (name)



d,e,f =1,2,"teja"
print (d)
print (e)
print(f)

str='Hello world'
print (str)
print (str[0])
print (str[2:5])
print (str[2:])
print  (str*2)
print (str + "TEST")

list =['abcd',786,2.23,'teja',70.2]
tinylist =[123, 'teja']
print (list)
print (list[0])
print (list[1:3])
print (list[2:])
print (tinylist *2)
print (list+tinylist)

tuple =("abcd",786,2.23,'teja',70.2)
tinytuple =(123,'teja')
print (tuple)
print (tuple[0])
print (tuple[1:3])
print (tuple[2:])
print (tinytuple *2)
print (tuple + tinytuple)

dict={}
dict['one'] ="teja"
dict [2] ="123"
tinydict ={'name':'teja','code':6734,'dept':'sales'}
print (dict['one'])
print (dict[2])
print (tinydict)
print (tinydict.keys())
print (tinydict.values())